# Profile: CLOUD - AWS RDS

# Database Configuration
spring.datasource.username=ecmasterdb
spring.datasource.password=2PxaGcEAyVzRUZayNv3f

# DataSource Config (usado pelo DataSourceConfig.java)
datasource.host=easycut-db.c160s2yyouk6.sa-east-1.rds.amazonaws.com
datasource.port=3306

# AWS S3 (opcional - descomentar se necessário)
#amazonProperties.endpointUrl=https://dominadev.s3.sa-east-1.amazonaws.com
#amazonProperties.accessKey=AKIARD6CI2CYENJGNF7D
#amazonProperties.secretKey=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
#amazonProperties.bucketName=dominadev

