# Configurações Comuns (Base)
server.port=8080
server.ssl.key-store=classpath:dominadev-keystore.p12
server.ssl.key-store-password=98520211
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=dominadev

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

