# Profile: LOCAL - Desenvolvimento Local

# Database Configuration
spring.datasource.username=root
spring.datasource.password=root

# DataSource Config (usado pelo DataSourceConfig.java)
datasource.host=localhost
datasource.port=3306

